kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default
  namespace: prod
subjects:
- kind: ServiceAccount
  name: default
  namespace: dev
  apiGroup: ""
roleRef:
  kind: Role
  name: firoj
  apiGroup: ""

